### ISSUE TITLE
v0.0.5: line 25 trim return &str and then .eq require &String

### ISSUE THREAD

**Issue by Sispheor** [rusticus-io/hangman#1]
So I replaced from
```rust
let line = line.trim();

        if search_string.eq(line) {
            println!("you win.");
            break;
        }

        if "quit".eq(line) {
            println!("bye.");
            break;
        }
```

To
```rust
//        let line = line.trim();

        if search_string.eq(&line) {
            println!("you win.");
            break;
        }

        if "quit".eq(&line) {
            println!("bye.");
            break;
        }
```

**Comment by thinkrapido** [comment]
Hi @Sispheor 
when we read a line from stdio via ```std::io::stdio().readline(&mut line)``` then the input contains a trailing \n because we also pressed the key ENTER.

Therefore we need let line = ```line.trim();```

**Comment by Sispheor** [comment]
Ok. But we should convert into a String then, isn't it? As it is required by "eq" method. Just that my ide complains about this part.
Maybe a false positive linter, the program compile anyway..
Thanks for your answer

**Comment by thinkrapido** [comment]
Yes, my IDE complains as well but it compiles perfectly.
